name = "supermemory"
compatibility_date = "2024-03-29"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"


kv_namespaces = [
	{ binding = "canvas_snaps", id = "fc56da7e95fd492b9d90eac6153b2731" },
	{ binding = "recommendations", id = "d7d358bc58ad4c6186fb1417f8504a70" }
]

env.production.kv_namespaces = [
	{ binding = "canvas_snaps", id = "fc56da7e95fd492b9d90eac6153b2731" },
	{ binding = "recommendations", id = "d7d358bc58ad4c6186fb1417f8504a70" }
]

[ai]
binding = "AI"

[placement]
mode = "smart"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "supermemory-r2"

[[d1_databases]]
binding = "DATABASE"
database_name = "supermemory-db-preview"
database_id = "2816fecb-1084-489a-baf1-ed01e4fe27a7"

[[env.production.d1_databases]]
binding = "DATABASE"
database_name = "supermemory-db-prod"
database_id = "02ddc5d1-1091-438e-8a0a-312c6922ca99"

[env.preview.ai]
binding = "AI"

[[env.preview.d1_databases]]
binding = "DATABASE"
database_name = "supermemory-db-preview"
database_id = "2816fecb-1084-489a-baf1-ed01e4fe27a7"

[env.production.ai]
binding = "AI"